require('dotenv').config()
const express=require('express'),cors=require('cors'),prisma=require('./lib/prisma')
const app=express()
app.use(cors())
app.use(express.json())
app.get('/health',async(req,res)=>{try{await prisma.$queryRaw`SELECT 1`;res.json({ok:true,db:'connected',time:new Date().toISOString()})}catch(e){res.status(503).json({ok:false,db:'error',detail:e.message})}})
app.use('/api/auth',require('./routes/auth'))
app.use('/api/zones',require('./routes/zones'))
app.use('/api/borrowers',require('./routes/borrowers'))
app.use('/api/investors',require('./routes/investors'))
app.use('/api/settings',require('./routes/settings'))
app.use('/api/ledger',require('./routes/ledger'))
app.use((req,res)=>res.status(404).json({error:`${req.method} ${req.path} not found`}))
app.use((err,req,res,next)=>{console.error('[ERROR]',err);const codes={'P2002':'Unique constraint failed','P2025':'Record not found','P2003':'Foreign key constraint failed'};if(err.code?.startsWith('P'))return res.status(400).json({error:codes[err.code]||err.message});res.status(500).json({error:'Internal server error',detail:err.message})})
const PORT=process.env.PORT||4000
const server=app.listen(PORT,()=>console.log(`FinMaint API on :${PORT}`))
const shutdown=async s=>{console.log(`\n${s} — shutting down`);server.close(async()=>{await prisma.$disconnect();process.exit(0)})}
process.on('SIGTERM',()=>shutdown('SIGTERM'))
process.on('SIGINT',()=>shutdown('SIGINT'))
