/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LenderRouteImport } from './routes/lender'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LenderIndexRouteImport } from './routes/lender.index'
import { Route as LenderZonesRouteImport } from './routes/lender.zones'
import { Route as LenderInvestorsRouteImport } from './routes/lender.investors'
import { Route as LenderCollectionRouteImport } from './routes/lender.collection'
import { Route as LenderBorrowersRouteImport } from './routes/lender.borrowers'
import { Route as LenderBorrowerIdRouteImport } from './routes/lender.borrower.$id'

const LenderRoute = LenderRouteImport.update({
  id: '/lender',
  path: '/lender',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LenderIndexRoute = LenderIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LenderRoute,
} as any)
const LenderZonesRoute = LenderZonesRouteImport.update({
  id: '/zones',
  path: '/zones',
  getParentRoute: () => LenderRoute,
} as any)
const LenderInvestorsRoute = LenderInvestorsRouteImport.update({
  id: '/investors',
  path: '/investors',
  getParentRoute: () => LenderRoute,
} as any)
const LenderCollectionRoute = LenderCollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => LenderRoute,
} as any)
const LenderBorrowersRoute = LenderBorrowersRouteImport.update({
  id: '/borrowers',
  path: '/borrowers',
  getParentRoute: () => LenderRoute,
} as any)
const LenderBorrowerIdRoute = LenderBorrowerIdRouteImport.update({
  id: '/borrower/$id',
  path: '/borrower/$id',
  getParentRoute: () => LenderRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lender': typeof LenderRouteWithChildren
  '/lender/borrowers': typeof LenderBorrowersRoute
  '/lender/collection': typeof LenderCollectionRoute
  '/lender/investors': typeof LenderInvestorsRoute
  '/lender/zones': typeof LenderZonesRoute
  '/lender/': typeof LenderIndexRoute
  '/lender/borrower/$id': typeof LenderBorrowerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/lender/borrowers': typeof LenderBorrowersRoute
  '/lender/collection': typeof LenderCollectionRoute
  '/lender/investors': typeof LenderInvestorsRoute
  '/lender/zones': typeof LenderZonesRoute
  '/lender': typeof LenderIndexRoute
  '/lender/borrower/$id': typeof LenderBorrowerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/lender': typeof LenderRouteWithChildren
  '/lender/borrowers': typeof LenderBorrowersRoute
  '/lender/collection': typeof LenderCollectionRoute
  '/lender/investors': typeof LenderInvestorsRoute
  '/lender/zones': typeof LenderZonesRoute
  '/lender/': typeof LenderIndexRoute
  '/lender/borrower/$id': typeof LenderBorrowerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/lender'
    | '/lender/borrowers'
    | '/lender/collection'
    | '/lender/investors'
    | '/lender/zones'
    | '/lender/'
    | '/lender/borrower/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/lender/borrowers'
    | '/lender/collection'
    | '/lender/investors'
    | '/lender/zones'
    | '/lender'
    | '/lender/borrower/$id'
  id:
    | '__root__'
    | '/'
    | '/lender'
    | '/lender/borrowers'
    | '/lender/collection'
    | '/lender/investors'
    | '/lender/zones'
    | '/lender/'
    | '/lender/borrower/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LenderRoute: typeof LenderRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/lender': {
      id: '/lender'
      path: '/lender'
      fullPath: '/lender'
      preLoaderRoute: typeof LenderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lender/': {
      id: '/lender/'
      path: '/'
      fullPath: '/lender/'
      preLoaderRoute: typeof LenderIndexRouteImport
      parentRoute: typeof LenderRoute
    }
    '/lender/zones': {
      id: '/lender/zones'
      path: '/zones'
      fullPath: '/lender/zones'
      preLoaderRoute: typeof LenderZonesRouteImport
      parentRoute: typeof LenderRoute
    }
    '/lender/investors': {
      id: '/lender/investors'
      path: '/investors'
      fullPath: '/lender/investors'
      preLoaderRoute: typeof LenderInvestorsRouteImport
      parentRoute: typeof LenderRoute
    }
    '/lender/collection': {
      id: '/lender/collection'
      path: '/collection'
      fullPath: '/lender/collection'
      preLoaderRoute: typeof LenderCollectionRouteImport
      parentRoute: typeof LenderRoute
    }
    '/lender/borrowers': {
      id: '/lender/borrowers'
      path: '/borrowers'
      fullPath: '/lender/borrowers'
      preLoaderRoute: typeof LenderBorrowersRouteImport
      parentRoute: typeof LenderRoute
    }
    '/lender/borrower/$id': {
      id: '/lender/borrower/$id'
      path: '/borrower/$id'
      fullPath: '/lender/borrower/$id'
      preLoaderRoute: typeof LenderBorrowerIdRouteImport
      parentRoute: typeof LenderRoute
    }
  }
}

interface LenderRouteChildren {
  LenderBorrowersRoute: typeof LenderBorrowersRoute
  LenderCollectionRoute: typeof LenderCollectionRoute
  LenderInvestorsRoute: typeof LenderInvestorsRoute
  LenderZonesRoute: typeof LenderZonesRoute
  LenderIndexRoute: typeof LenderIndexRoute
  LenderBorrowerIdRoute: typeof LenderBorrowerIdRoute
}

const LenderRouteChildren: LenderRouteChildren = {
  LenderBorrowersRoute: LenderBorrowersRoute,
  LenderCollectionRoute: LenderCollectionRoute,
  LenderInvestorsRoute: LenderInvestorsRoute,
  LenderZonesRoute: LenderZonesRoute,
  LenderIndexRoute: LenderIndexRoute,
  LenderBorrowerIdRoute: LenderBorrowerIdRoute,
}

const LenderRouteWithChildren =
  LenderRoute._addFileChildren(LenderRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LenderRoute: LenderRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
